# Generated by Django 5.2.7 on 2025-11-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_facturacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
