# Generated by Django 5.2.7 on 2025-11-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_fecha_facturacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='created_at',
            new_name='fecha_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_facturacion',
        ),
    ]
