# Generated by Django 5.2.7 on 2025-11-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En preparación'), ('VIAJANDO', 'Viajando'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
    ]
