[build]
builder = "Nixpacks"

[deploy]
startCommand = "gunicorn SistemaDePedidos.wsgi:application"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[variables]
PYTHON_VERSION = "3.13.4"
