# Generated by Django 5.2.7 on 2025-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_en_oferta_producto_precio_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='¿Está en oferta?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio en oferta'),
        ),
    ]
